services:
  mongodb1: # Short
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rizki
      MONGO_INITDB_ROOT_PASSWORD: rizki
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db"

  mongodb2: # Long
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rizki
      MONGO_INITDB_ROOT_PASSWORD: rizki
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: bind
        source: ./data-mongo2
        target: /data/db
        read_only: false