services:
  monogdb-example: # Short
    image: mongo:latest
    container_name: monogdb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rizki
      MONGO_INITDB_ROOT_PASSWORD: rizki
      MONGO_INITDB_DATABASE: admin

  mongodb-express-example: # Long
    image: mongo-express:latest
    container_name: mongodb-express-example
    depends_on:
      - monogdb-example
    environment:
      ME_CONFIG_MONGODB_SERVER: monogdb-example
      ME_CONFIG_MONGODB_ADMINUSERNAME: rizki
      ME_CONFIG_MONGODB_ADMINPASSWORD: rizki