services:
  app: 
    container_name: app1
    build: 
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.0"
    environment: 
      - "APP_PORT=8080"
      - "MODE=local"
    ports:
      - 8080:8080